version: "20.10.21"

services:
  mongo:
    image:  mongo
    container_name: mongo
    ports:
      - 27017:27017
      
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      -5672:5672
      -15672:15672
    volumes:
      -rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  rabbitmqdata: